// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvtwsfothnnyufxmcpdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dHdzZm90aG5ueXVmeG1jcGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjA0MDcsImV4cCI6MjA2MzkzNjQwN30.gtv4TxlF4lfPF8iKO6V_Kli-nsEnU1BonYtSb8F6Ojg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);